# Generated by Django 5.2 on 2025-05-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_completedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='specialty',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mentor'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(verbose_name='Bio / tajriba'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='To‘liq ism'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(upload_to='mentors/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
