# Generated by Django 5.2 on 2025-05-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mentor_specialty_mentor_telegram_alter_course_mentor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['full_name'], 'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentorlar'},
        ),
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(verbose_name='Bio / Tajriba'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram profil'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='specialty',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram profil'),
        ),
    ]
