# Generated by Django 5.2 on 2025-05-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_mentor_options_alter_mentor_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['-id'], 'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentorlar'},
        ),
    ]
