# Generated by Django 5.2 on 2025-05-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
