# Generated by Django 5.2 on 2025-05-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ake.fx haqida', max_length=200)),
                ('content', models.TextField(verbose_name='Asosiy matn')),
                ('news_title', models.CharField(default='Yangiliklar', max_length=200)),
                ('news', models.TextField(blank=True, verbose_name='Yangiliklar (HTML yoki markdown)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Asosiy rasm')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'About sahifa',
                'verbose_name_plural': 'About sahifa',
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
