# Generated by Django 5.2 on 2025-05-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_aboutpage_alter_lesson_video_url_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(blank=True, verbose_name='Bizning vazifamiz'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='statistics',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'students': 1200, 'courses': 24, 'mentors': 15, 'satisfaction': 98}", verbose_name='Statistika'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_description',
            field=models.TextField(blank=True, verbose_name='Jamoa haqida'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_title',
            field=models.CharField(default='Bizning jamoa', max_length=200, verbose_name='Jamoa sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video havolasi', verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Bizning maqsadimiz'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='main_image',
            field=models.ImageField(blank=True, default=1, upload_to='about/', verbose_name='Asosiy rasm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='news',
            field=models.TextField(blank=True, verbose_name='Yangiliklar (HTML)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='news_title',
            field=models.CharField(default='Yangiliklar', max_length=200, verbose_name='Yangiliklar sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='Ake.fx haqida', max_length=200, verbose_name='Sarlavha'),
        ),
    ]
