# Generated by Django 5.2 on 2025-05-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_aboutpage_created_at_aboutpage_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='statistics',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'students': 1200, 'courses': 24, 'mentors': 15, 'satisfaction': 98}", null=True, verbose_name='Statistika'),
        ),
    ]
