# Generated by Django 5.2 on 2025-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='00:00', max_length=50, verbose_name='Davomiyligi'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Bepul dars'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video havolasi'),
        ),
    ]
