# Generated by Django 5.2 on 2025-05-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_lesson_options_lesson_duration_lesson_is_free_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
    ]
