# Generated by Django 5.2 on 2025-05-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default=1, verbose_name="To'liq matn"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='news/', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
