# Generated by Django 5.2 on 2025-06-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_news_content_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
