# Generated by Django 5.2 on 2025-06-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_courseenrollment_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='_progress',
            field=models.IntegerField(db_column='progress', default=0),
        ),
    ]
