# Generated by Django 5.2 on 2025-07-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_courseenrollment__progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=100)),
                ('video_url', models.URLField(help_text='YouTube yoki boshqa video havolasi')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
