# Generated by Django 5.2 on 2025-07-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_studentvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='studentvideo',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
